name: .NET

on:
  push:
    branches: [ master ]
    paths:
    - 'Wordsmith.Api/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'Wordsmith.Api/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      working-directory: Wordsmith.Api
      run: dotnet restore
    - name: Build
      working-directory: Wordsmith.Api
      run: dotnet build --no-restore
    - name: Test
      working-directory: Wordsmith.Api
      run: dotnet test --no-build --verbosity normal
